BookStore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^BookStoreApp/', include('BookStoreApp.urls', namespace='BookStoreApp')),
    url(r'^admin/', include(admin.site.urls)),
]

BookStoreApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^book/(?P<book_id>[0-9]+)/$', views.book_detail, name='bookdetail'),
    url(r'^author/(?P<author_id>[0-9]+)/$', views.author_detail, name='authordetail'),
    url(r'^book/(?P<book_id>[0-9]+)/review/$', views.book_review, name='bookreview'),
]

BookStoreApp/models.py
from django.db import models

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return self.last_name + ", " + self.first_name

class Book(models.Model):
    author = models.ForeignKey(Author)
    book_title = models.CharField(max_length=100)

    def __str__(self):
        return self.book_title

class BookReview(models.Model):
    book = models.ForeignKey(Book)
    stars = models.IntegerField()
    review_text = models.CharField(max_length=200)

    def __str__(self):
        return self.review_text

BookStoreApp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render

from .models import Book, Author, BookReview

def index(request):
    book_list = Book.objects.order_by('-book_title')[:5]
    context = {'book_list': book_list}
    return render(request, 'BookStoreApp/index.html', context)

def book_detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    context = {'book': book}
    return render(request, 'BookStoreApp/book_detail.html', context)

def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    context = {'author': author}
    return render(request, 'BookStoreApp/author_detail.html', context)

def book_review(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    new_review = book.bookreview_set.create(review_text=request.POST['review'], stars=request.POST['stars'])
    stars = avg_book_stars(book_id)
    context = {'book':book, 'stars':stars}
    return render(request, 'BookStoreApp/book_detail.html', context)

def avg_book_stars(book_id):
    book = get_object_or_404(Book, pk=book_id)
    count = 0
    stars = 0
    for review in book.bookreview_set.all():
        stars = review.stars + stars
        count += 1
    stars = (2*stars) // count
    stars = stars/2 # This makes stars round to the nearest half integer
    return stars

templates/BookStoreApp/author_detail.html
<h1>{{ author }}</h1>

<ul>
    {% for book in author.book_set.all %}
    <li>{{book}}</li>
    {%endfor%}
</ul>

templates/BookStoreApp/book_detail.html
<h1>{{book.book_title}}</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}
<h4>This book is rated {{stars}}/5</h4>
<ul>
{% for review in book.bookreview_set.all %}
<li>{{ review.review_text }}</li>
{% endfor %}
</ul>

<h2>Write A Review</h2>
<form action="{% url 'BookStoreApp:bookreview' book.id %}" method="post">
    {% csrf_token %}
    <select name="stars" id="stars">
        <option value=1>1 Star</option>
        <option value=2>2 Stars</option>
        <option value=3>3 Stars</option>
        <option value=4>4 Stars</option>
        <option value=5>5 Stars</option>
    </select>
    <input type="text" name="review" id="review"/>
    <input type="submit"/>
</form>

templates/BookStoreApp/book_review.html
<p>success</p>

templates/BookStoreApp/index.html
<h1>Welcome to the Book Store</h1>

<p>Current Books:</p>
{% if book_list %}
    <ul>
    {% for book in book_list %}
        <li><a href="{% url 'BookStoreApp:bookdetail' book.id %}">{{ book.book_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Books are available.</p>
{% endif %}